git:
  depth: false

language: node_js
node_js:
  - "node"

branches:
  only:
    - exp

cache:
  yarn: true
  directories:
    - "node_modules"


before_install: sudo apt-get -qq update && sudo apt-get install -y texlive-full
script: yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: build
  on:
    branch: exp
  target-branch: master

sudo: true
