git:
  depth: false

language: node_js
node_js:
  - "node" # upath@1.0.4 node engine compatability

branches:
  only:
    - exp

cache:
  yarn: true
  directories:
    - "node_modules"

script: yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: build
  on:
    branch: exp
  target-branch: master

sudo: false
